cat encoded.enc |  python3 xcat/xcat.py -n 0x0
cat encoded.enc |  python3 xcat/xcat.py -n 0x1
cat encoded.enc |  python3 xcat/xcat.py -n 0x2
cat encoded.enc |  python3 xcat/xcat.py -n 0x3
cat encoded.enc |  python3 xcat/xcat.py -n 0x4
cat encoded.enc |  python3 xcat/xcat.py -n 0x5
cat encoded.enc |  python3 xcat/xcat.py -n 0x6
cat encoded.enc |  python3 xcat/xcat.py -n 0x7
cat encoded.enc |  python3 xcat/xcat.py -n 0x8
cat encoded.enc |  python3 xcat/xcat.py -n 0x9
cat encoded.enc |  python3 xcat/xcat.py -n 0xa
cat encoded.enc |  python3 xcat/xcat.py -n 0xb
cat encoded.enc |  python3 xcat/xcat.py -n 0xc
cat encoded.enc |  python3 xcat/xcat.py -n 0xd
cat encoded.enc |  python3 xcat/xcat.py -n 0xe
cat encoded.enc |  python3 xcat/xcat.py -n 0xf
cat encoded.enc |  python3 xcat/xcat.py -n 0x10
cat encoded.enc |  python3 xcat/xcat.py -n 0x11
cat encoded.enc |  python3 xcat/xcat.py -n 0x12
cat encoded.enc |  python3 xcat/xcat.py -n 0x13
cat encoded.enc |  python3 xcat/xcat.py -n 0x14
cat encoded.enc |  python3 xcat/xcat.py -n 0x15
cat encoded.enc |  python3 xcat/xcat.py -n 0x16
cat encoded.enc |  python3 xcat/xcat.py -n 0x17
cat encoded.enc |  python3 xcat/xcat.py -n 0x18
cat encoded.enc |  python3 xcat/xcat.py -n 0x19
cat encoded.enc |  python3 xcat/xcat.py -n 0x1a
cat encoded.enc |  python3 xcat/xcat.py -n 0x1b
cat encoded.enc |  python3 xcat/xcat.py -n 0x1c
cat encoded.enc |  python3 xcat/xcat.py -n 0x1d
cat encoded.enc |  python3 xcat/xcat.py -n 0x1e
cat encoded.enc |  python3 xcat/xcat.py -n 0x1f
cat encoded.enc |  python3 xcat/xcat.py -n 0x20
cat encoded.enc |  python3 xcat/xcat.py -n 0x21
cat encoded.enc |  python3 xcat/xcat.py -n 0x22
cat encoded.enc |  python3 xcat/xcat.py -n 0x23
cat encoded.enc |  python3 xcat/xcat.py -n 0x24
cat encoded.enc |  python3 xcat/xcat.py -n 0x25
cat encoded.enc |  python3 xcat/xcat.py -n 0x26
cat encoded.enc |  python3 xcat/xcat.py -n 0x27
cat encoded.enc |  python3 xcat/xcat.py -n 0x28
cat encoded.enc |  python3 xcat/xcat.py -n 0x29
cat encoded.enc |  python3 xcat/xcat.py -n 0x2a
cat encoded.enc |  python3 xcat/xcat.py -n 0x2b
cat encoded.enc |  python3 xcat/xcat.py -n 0x2c
cat encoded.enc |  python3 xcat/xcat.py -n 0x2d
cat encoded.enc |  python3 xcat/xcat.py -n 0x2e
cat encoded.enc |  python3 xcat/xcat.py -n 0x2f
cat encoded.enc |  python3 xcat/xcat.py -n 0x30
cat encoded.enc |  python3 xcat/xcat.py -n 0x31
cat encoded.enc |  python3 xcat/xcat.py -n 0x32
cat encoded.enc |  python3 xcat/xcat.py -n 0x33
cat encoded.enc |  python3 xcat/xcat.py -n 0x34
cat encoded.enc |  python3 xcat/xcat.py -n 0x35
cat encoded.enc |  python3 xcat/xcat.py -n 0x36
cat encoded.enc |  python3 xcat/xcat.py -n 0x37
cat encoded.enc |  python3 xcat/xcat.py -n 0x38
cat encoded.enc |  python3 xcat/xcat.py -n 0x39
cat encoded.enc |  python3 xcat/xcat.py -n 0x3a
cat encoded.enc |  python3 xcat/xcat.py -n 0x3b
cat encoded.enc |  python3 xcat/xcat.py -n 0x3c
cat encoded.enc |  python3 xcat/xcat.py -n 0x3d
cat encoded.enc |  python3 xcat/xcat.py -n 0x3e
cat encoded.enc |  python3 xcat/xcat.py -n 0x3f
cat encoded.enc |  python3 xcat/xcat.py -n 0x40
cat encoded.enc |  python3 xcat/xcat.py -n 0x41
cat encoded.enc |  python3 xcat/xcat.py -n 0x42
cat encoded.enc |  python3 xcat/xcat.py -n 0x43
cat encoded.enc |  python3 xcat/xcat.py -n 0x44
cat encoded.enc |  python3 xcat/xcat.py -n 0x45
cat encoded.enc |  python3 xcat/xcat.py -n 0x46
cat encoded.enc |  python3 xcat/xcat.py -n 0x47
cat encoded.enc |  python3 xcat/xcat.py -n 0x48
cat encoded.enc |  python3 xcat/xcat.py -n 0x49
cat encoded.enc |  python3 xcat/xcat.py -n 0x4a
cat encoded.enc |  python3 xcat/xcat.py -n 0x4b
cat encoded.enc |  python3 xcat/xcat.py -n 0x4c
cat encoded.enc |  python3 xcat/xcat.py -n 0x4d
cat encoded.enc |  python3 xcat/xcat.py -n 0x4e
cat encoded.enc |  python3 xcat/xcat.py -n 0x4f
cat encoded.enc |  python3 xcat/xcat.py -n 0x50
cat encoded.enc |  python3 xcat/xcat.py -n 0x51
cat encoded.enc |  python3 xcat/xcat.py -n 0x52
cat encoded.enc |  python3 xcat/xcat.py -n 0x53
cat encoded.enc |  python3 xcat/xcat.py -n 0x54
cat encoded.enc |  python3 xcat/xcat.py -n 0x55
cat encoded.enc |  python3 xcat/xcat.py -n 0x56
cat encoded.enc |  python3 xcat/xcat.py -n 0x57
cat encoded.enc |  python3 xcat/xcat.py -n 0x58
cat encoded.enc |  python3 xcat/xcat.py -n 0x59
cat encoded.enc |  python3 xcat/xcat.py -n 0x5a
cat encoded.enc |  python3 xcat/xcat.py -n 0x5b
cat encoded.enc |  python3 xcat/xcat.py -n 0x5c
cat encoded.enc |  python3 xcat/xcat.py -n 0x5d
cat encoded.enc |  python3 xcat/xcat.py -n 0x5e
cat encoded.enc |  python3 xcat/xcat.py -n 0x5f
cat encoded.enc |  python3 xcat/xcat.py -n 0x60
cat encoded.enc |  python3 xcat/xcat.py -n 0x61
cat encoded.enc |  python3 xcat/xcat.py -n 0x62
cat encoded.enc |  python3 xcat/xcat.py -n 0x63
cat encoded.enc |  python3 xcat/xcat.py -n 0x64
cat encoded.enc |  python3 xcat/xcat.py -n 0x65
cat encoded.enc |  python3 xcat/xcat.py -n 0x66
cat encoded.enc |  python3 xcat/xcat.py -n 0x67
cat encoded.enc |  python3 xcat/xcat.py -n 0x68
cat encoded.enc |  python3 xcat/xcat.py -n 0x69
cat encoded.enc |  python3 xcat/xcat.py -n 0x6a
cat encoded.enc |  python3 xcat/xcat.py -n 0x6b
cat encoded.enc |  python3 xcat/xcat.py -n 0x6c
cat encoded.enc |  python3 xcat/xcat.py -n 0x6d
cat encoded.enc |  python3 xcat/xcat.py -n 0x6e
cat encoded.enc |  python3 xcat/xcat.py -n 0x6f
cat encoded.enc |  python3 xcat/xcat.py -n 0x70
cat encoded.enc |  python3 xcat/xcat.py -n 0x71
cat encoded.enc |  python3 xcat/xcat.py -n 0x72
cat encoded.enc |  python3 xcat/xcat.py -n 0x73
cat encoded.enc |  python3 xcat/xcat.py -n 0x74
cat encoded.enc |  python3 xcat/xcat.py -n 0x75
cat encoded.enc |  python3 xcat/xcat.py -n 0x76
cat encoded.enc |  python3 xcat/xcat.py -n 0x77
cat encoded.enc |  python3 xcat/xcat.py -n 0x78
cat encoded.enc |  python3 xcat/xcat.py -n 0x79
cat encoded.enc |  python3 xcat/xcat.py -n 0x7a
cat encoded.enc |  python3 xcat/xcat.py -n 0x7b
cat encoded.enc |  python3 xcat/xcat.py -n 0x7c
cat encoded.enc |  python3 xcat/xcat.py -n 0x7d
cat encoded.enc |  python3 xcat/xcat.py -n 0x7e
cat encoded.enc |  python3 xcat/xcat.py -n 0x7f
cat encoded.enc |  python3 xcat/xcat.py -n 0x80
cat encoded.enc |  python3 xcat/xcat.py -n 0x81
cat encoded.enc |  python3 xcat/xcat.py -n 0x82
cat encoded.enc |  python3 xcat/xcat.py -n 0x83
cat encoded.enc |  python3 xcat/xcat.py -n 0x84
cat encoded.enc |  python3 xcat/xcat.py -n 0x85
cat encoded.enc |  python3 xcat/xcat.py -n 0x86
cat encoded.enc |  python3 xcat/xcat.py -n 0x87
cat encoded.enc |  python3 xcat/xcat.py -n 0x88
cat encoded.enc |  python3 xcat/xcat.py -n 0x89
cat encoded.enc |  python3 xcat/xcat.py -n 0x8a
cat encoded.enc |  python3 xcat/xcat.py -n 0x8b
cat encoded.enc |  python3 xcat/xcat.py -n 0x8c
cat encoded.enc |  python3 xcat/xcat.py -n 0x8d
cat encoded.enc |  python3 xcat/xcat.py -n 0x8e
cat encoded.enc |  python3 xcat/xcat.py -n 0x8f
cat encoded.enc |  python3 xcat/xcat.py -n 0x90
cat encoded.enc |  python3 xcat/xcat.py -n 0x91
cat encoded.enc |  python3 xcat/xcat.py -n 0x92
cat encoded.enc |  python3 xcat/xcat.py -n 0x93
cat encoded.enc |  python3 xcat/xcat.py -n 0x94
cat encoded.enc |  python3 xcat/xcat.py -n 0x95
cat encoded.enc |  python3 xcat/xcat.py -n 0x96
cat encoded.enc |  python3 xcat/xcat.py -n 0x97
cat encoded.enc |  python3 xcat/xcat.py -n 0x98
cat encoded.enc |  python3 xcat/xcat.py -n 0x99
cat encoded.enc |  python3 xcat/xcat.py -n 0x9a
cat encoded.enc |  python3 xcat/xcat.py -n 0x9b
cat encoded.enc |  python3 xcat/xcat.py -n 0x9c
cat encoded.enc |  python3 xcat/xcat.py -n 0x9d
cat encoded.enc |  python3 xcat/xcat.py -n 0x9e
cat encoded.enc |  python3 xcat/xcat.py -n 0x9f
cat encoded.enc |  python3 xcat/xcat.py -n 0xa0
cat encoded.enc |  python3 xcat/xcat.py -n 0xa1
cat encoded.enc |  python3 xcat/xcat.py -n 0xa2
cat encoded.enc |  python3 xcat/xcat.py -n 0xa3
cat encoded.enc |  python3 xcat/xcat.py -n 0xa4
cat encoded.enc |  python3 xcat/xcat.py -n 0xa5
cat encoded.enc |  python3 xcat/xcat.py -n 0xa6
cat encoded.enc |  python3 xcat/xcat.py -n 0xa7
cat encoded.enc |  python3 xcat/xcat.py -n 0xa8
cat encoded.enc |  python3 xcat/xcat.py -n 0xa9
cat encoded.enc |  python3 xcat/xcat.py -n 0xaa
cat encoded.enc |  python3 xcat/xcat.py -n 0xab
cat encoded.enc |  python3 xcat/xcat.py -n 0xac
cat encoded.enc |  python3 xcat/xcat.py -n 0xad
cat encoded.enc |  python3 xcat/xcat.py -n 0xae
cat encoded.enc |  python3 xcat/xcat.py -n 0xaf
cat encoded.enc |  python3 xcat/xcat.py -n 0xb0
cat encoded.enc |  python3 xcat/xcat.py -n 0xb1
cat encoded.enc |  python3 xcat/xcat.py -n 0xb2
cat encoded.enc |  python3 xcat/xcat.py -n 0xb3
cat encoded.enc |  python3 xcat/xcat.py -n 0xb4
cat encoded.enc |  python3 xcat/xcat.py -n 0xb5
cat encoded.enc |  python3 xcat/xcat.py -n 0xb6
cat encoded.enc |  python3 xcat/xcat.py -n 0xb7
cat encoded.enc |  python3 xcat/xcat.py -n 0xb8
cat encoded.enc |  python3 xcat/xcat.py -n 0xb9
cat encoded.enc |  python3 xcat/xcat.py -n 0xba
cat encoded.enc |  python3 xcat/xcat.py -n 0xbb
cat encoded.enc |  python3 xcat/xcat.py -n 0xbc
cat encoded.enc |  python3 xcat/xcat.py -n 0xbd
cat encoded.enc |  python3 xcat/xcat.py -n 0xbe
cat encoded.enc |  python3 xcat/xcat.py -n 0xbf
cat encoded.enc |  python3 xcat/xcat.py -n 0xc0
cat encoded.enc |  python3 xcat/xcat.py -n 0xc1
cat encoded.enc |  python3 xcat/xcat.py -n 0xc2
cat encoded.enc |  python3 xcat/xcat.py -n 0xc3
cat encoded.enc |  python3 xcat/xcat.py -n 0xc4
cat encoded.enc |  python3 xcat/xcat.py -n 0xc5
cat encoded.enc |  python3 xcat/xcat.py -n 0xc6
cat encoded.enc |  python3 xcat/xcat.py -n 0xc7
cat encoded.enc |  python3 xcat/xcat.py -n 0xc8
cat encoded.enc |  python3 xcat/xcat.py -n 0xc9
cat encoded.enc |  python3 xcat/xcat.py -n 0xca
cat encoded.enc |  python3 xcat/xcat.py -n 0xcb
cat encoded.enc |  python3 xcat/xcat.py -n 0xcc
cat encoded.enc |  python3 xcat/xcat.py -n 0xcd
cat encoded.enc |  python3 xcat/xcat.py -n 0xce
cat encoded.enc |  python3 xcat/xcat.py -n 0xcf
cat encoded.enc |  python3 xcat/xcat.py -n 0xd0
cat encoded.enc |  python3 xcat/xcat.py -n 0xd1
cat encoded.enc |  python3 xcat/xcat.py -n 0xd2
cat encoded.enc |  python3 xcat/xcat.py -n 0xd3
cat encoded.enc |  python3 xcat/xcat.py -n 0xd4
cat encoded.enc |  python3 xcat/xcat.py -n 0xd5
cat encoded.enc |  python3 xcat/xcat.py -n 0xd6
cat encoded.enc |  python3 xcat/xcat.py -n 0xd7
cat encoded.enc |  python3 xcat/xcat.py -n 0xd8
cat encoded.enc |  python3 xcat/xcat.py -n 0xd9
cat encoded.enc |  python3 xcat/xcat.py -n 0xda
cat encoded.enc |  python3 xcat/xcat.py -n 0xdb
cat encoded.enc |  python3 xcat/xcat.py -n 0xdc
cat encoded.enc |  python3 xcat/xcat.py -n 0xdd
cat encoded.enc |  python3 xcat/xcat.py -n 0xde
cat encoded.enc |  python3 xcat/xcat.py -n 0xdf
cat encoded.enc |  python3 xcat/xcat.py -n 0xe0
cat encoded.enc |  python3 xcat/xcat.py -n 0xe1
cat encoded.enc |  python3 xcat/xcat.py -n 0xe2
cat encoded.enc |  python3 xcat/xcat.py -n 0xe3
cat encoded.enc |  python3 xcat/xcat.py -n 0xe4
cat encoded.enc |  python3 xcat/xcat.py -n 0xe5
cat encoded.enc |  python3 xcat/xcat.py -n 0xe6
cat encoded.enc |  python3 xcat/xcat.py -n 0xe7
cat encoded.enc |  python3 xcat/xcat.py -n 0xe8
cat encoded.enc |  python3 xcat/xcat.py -n 0xe9
cat encoded.enc |  python3 xcat/xcat.py -n 0xea
cat encoded.enc |  python3 xcat/xcat.py -n 0xeb
cat encoded.enc |  python3 xcat/xcat.py -n 0xec
cat encoded.enc |  python3 xcat/xcat.py -n 0xed
cat encoded.enc |  python3 xcat/xcat.py -n 0xee
cat encoded.enc |  python3 xcat/xcat.py -n 0xef
cat encoded.enc |  python3 xcat/xcat.py -n 0xf0
cat encoded.enc |  python3 xcat/xcat.py -n 0xf1
cat encoded.enc |  python3 xcat/xcat.py -n 0xf2
cat encoded.enc |  python3 xcat/xcat.py -n 0xf3
cat encoded.enc |  python3 xcat/xcat.py -n 0xf4
cat encoded.enc |  python3 xcat/xcat.py -n 0xf5
cat encoded.enc |  python3 xcat/xcat.py -n 0xf6
cat encoded.enc |  python3 xcat/xcat.py -n 0xf7
cat encoded.enc |  python3 xcat/xcat.py -n 0xf8
cat encoded.enc |  python3 xcat/xcat.py -n 0xf9
cat encoded.enc |  python3 xcat/xcat.py -n 0xfa
cat encoded.enc |  python3 xcat/xcat.py -n 0xfb
cat encoded.enc |  python3 xcat/xcat.py -n 0xfc
cat encoded.enc |  python3 xcat/xcat.py -n 0xfd
cat encoded.enc |  python3 xcat/xcat.py -n 0xfe
cat encoded.enc |  python3 xcat/xcat.py -n 0xff
